import pygame
#이미지를 가져온다
player = pygame.image.load("resources/my_resources/player_ready_Red.png")
ball_room = pygame.image.load("resources/my_resources/magic_room.png")
card_room = pygame.image.load("resources/my_resources/card_room.png")
pave_road = pygame.image.load("resources/my_resources/pave_road.png")
ground = pygame.image.load("resources/my_resources/ground.png")
tent = pygame.image.load("resources/my_resources/tent.png")
tent_road = pygame.image.load("resources/my_resources/tent_road.png")
castle = pygame.image.load("resources/my_resources/castle_wall.png")
card_Red = pygame.image.load("resources/my_resources/Red_card_1.png")
zombie = pygame.image.load("resources/my_resources/zombie.png")
zombie_barrier = pygame.image.load("resources/my_resources/zombie_barrier.png")
nighthorror = pygame.image.load("resources/my_resources/nighthorror.png")
ling = pygame.image.load("resources/my_resources/nighthorror_ling.png")
cannon = pygame.image.load("resources/my_resources/cannon.png")
ball = pygame.image.load("resources/my_resources/cannon_ball.png")
crawler = pygame.image.load("resources/my_resources/crawler.png")
sting = pygame.image.load("resources/my_resources/sting.png")
seer = pygame.image.load("resources/my_resources/overseer.png")
black = pygame.image.load("resources/my_resources/Black_lord.png")
grey = pygame.image.load("resources/my_resources/Grey_lord.png")
final = pygame.image.load("resources/my_resources/Final_Lord.png")
arrow_Red = pygame.image.load("resources/my_resources/arrow_Red.png")